### ISSUE TITLE
start service error

### ISSUE THREAD

**Issue by narakai** [aaaamirabbas/nekoray-macos#1]
Use NekoBox and import a working VMess config. After clicking "start", an error occurred saying: "start service: open geoip database: error opening database: invalid MaxMind DB file".

**Comment by narakai** [comment]
I think the issue is caused by selecting:

Routing Settings  - preset -  Bypass LAN and China

**Comment by narakai** [comment]
Seems app can not find where geoip.dat and geosite.dat are, is there a way I can config this manually?

**Comment by aaaamirabbas** [comment]
@narakai Thank you for reporting the problem.
I found the problem, I will upload a new version in a few hours.
