### ISSUE TITLE
还有一个问题

### ISSUE THREAD

**Issue by lxtx528** [aaaamirabbas/nekoray-macos#11]
在开启系统代理上网，退出系统代理后，电脑就没有办法联网了，需要手动到网络设置里点击去掉网页代理，安全网络代理，socks代理才能重新上网。

**Comment by aaaamirabbas** [comment]
Hi I didn't notice your problem, after disabling System Proxy, proxy settings from your system will be erased automatically.
Please write more about your problem, and please write English.
