### ISSUE TITLE
m2 air 13.2.1 经常出现启动了，但是点不开界面情况。

### ISSUE THREAD

**Issue by cantonadong** [aaaamirabbas/nekoray-macos#12]
虽然路由是通的，就怕万一线路挂了，都没法切换。

**Comment by aaaamirabbas** [comment]
I translated your issue to English with Google, unfortunately I did not understand what your problem is.
Please express your problem in **English** and carefully.

**Comment by cantonadong** [comment]
m2 13.2.1，nekoray 2.26。
The software can be started normally, but the software interface cannot be displayed, and neither exiting nor restarting can solve the problem.

**Comment by aaaamirabbas** [comment]
Which version did you download, the arm version?
Are you getting an error?
Install version 2.12 and test it, does it work well?

**Comment by cantonadong** [comment]
I have found a way to reproduce the problem. If the software starts and the icon is displayed on the top status bar, you can click the icon on the top to display the software interface. However, the software interface cannot be displayed by clicking the dock icon at the bottom, and the owner will be stuck. 
arm version 2.26

**Comment by aaaamirabbas** [comment]
I have the problem myself.
This is not the problem at the time of construction, and the problem is the source.
Make this problem in the main repo.
https://github.com/MatsuriDayo/nekoray/issues
